### ISSUE TITLE
Not able to run the mozzle binary file

### ISSUE THREAD

**Issue by vishalchds** [Bo0mer/mozzle#16]
While i run  =>mozzle_windows_amd64 -use-cf-cli-target
ran in to below error:
mozzle: error reading CF CLI config: error open ".cf\\config.json": open .cf\config.json: The system cannot find the path specified.
I have no clue what is missing. Please help me

**Comment by Bo0mer** [comment]
Hi,

Indeed this is an issue with the mozzle cli. It looks for the CF CLI configuration file in the wrong place. I'll provide a fix as soon as possible.

Thanks,
Ivan

**Comment by Bo0mer** [comment]
Could you try with the binary from v0.4.1 - https://github.com/Bo0mer/mozzle/releases/tag/v0.4.1

Thanks!

**Comment by vishalchds** [comment]
Ya this binary file is working...But their are many failed requests showing up. Like error fetching app: doing page request failed, error streaming from firehose, Please ask cloudfoundry to check configuration.etc. Am i missing something. Like i have followed all steps you have given.

**Comment by Bo0mer** [comment]
Could you provide the exact output? Otherwise it's really hard to tell what causes your problem. 

Thanks.

**Comment by vishalchds** [comment]
Thank you. Solved the issue.
